apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name}}-lb
  namespace: {{ .Release.Namespace}}
spec:
  type: LoadBalancer
  selector:
{{ include "selector.labels" . | indent 4}}
  ports:
    - protocol: TCP
      port: 8080          # expose or external or service port
      targetPort: 8080  #container port
